### ISSUE TITLE
Comply with the rules for Among Us mods

### ISSUE THREAD

**Issue by JohnyDaison** [VedalAI/neuro-amongus#10]
Here https://www.innersloth.com/among-us-mod-policy/ it is stated that the mod stamp should be shown in-game and the disclaimer should be written somewhere on the mod's page.
Feel free to close this one if it is not relevant (if this doesn't count as a mod?), but I think since the plan is to widely distribute this to collect as much data as possible, all bases should be covered.

**Comment by Vedal987** [comment]
Good point, addressed in e820c4363e20aaab8d8e4cca9e78930e268acc4b. I think BepInEx/Reactor means that the mod stamp will be shown in game.
