### ISSUE TITLE
Auto completing the Align Engine Output task on the skeld is broken

### ISSUE THREAD

**Issue by Vedal987** [VedalAI/neuro-amongus#12]
I haven't looked into this but I imagine there are other tasks which are broken too.

**Comment by oleg20111511** [comment]
Fixed all not-sabotage tasks in Skeld in PR #17

**Comment by oleg20111511** [comment]
Also, I wonder about how auto completion of tasks opens any task that is close enough to Neuro. Since her AI input will contain direction toward a single specific task (by the last draft I seen, that is), should we also limit the auto completion to that specific task?

**Comment by Vedal987** [comment]
Thanks for the fix!

> Also, I wonder about how auto completion of tasks opens any task that is close enough to Neuro. Since her AI input will contain direction toward a single specific task (by the last draft I seen, that is), should we also limit the auto completion to that specific task?

Probably not, although we will improve the "next task" system to prioritize tasks that are closer.
