### ISSUE TITLE
consider using Unity Explorer?

### ISSUE THREAD

**Issue by AriesAlex** [VedalAI/neuro-amongus#19]
https://github.com/sinai-dev/UnityExplorer
![image](https://user-images.githubusercontent.com/39626061/227724370-858df335-e6fd-4b88-abdb-151818b0ee95.png)

Pretty useful thing, I used it when modifying other unity games

I tried using it in Among Us with BepInEx/MelonLoader and it doesn't work: bepinex didnt see it and melon throws error
There's way to use it standalone but it requires injecting dll, dependencies and manually creating instance

Feel free to just close this issue, it's just idea if someone would can make it work

**Comment by ScrubN** [comment]
Looking at issue reports and doing limited testing, it seems that Unity Explorer is not compatible with current-patch among us
