### ISSUE TITLE
More project refactoring

### ISSUE THREAD

**Issue by Alexejhero** [VedalAI/neuro-amongus#29]
- [x] The current pathfinding system is all over the place. At the moment, `PathfindingHandler`, `MovementHandler` and `TasksHandler` all touch movement/pathfinding fields. These should be refactored.
- [x] Currently tasks are being opened using heinous methods, we should instead merge `MinigameHandler` and `TasksHandler` and allow each task to specify when it should be opened using something like MinigameSolver in #26 
- [x] `VisionHandler` is a mess, it should be refactored to reduce duplicated code, reduce method complexity, and stuff like that
- [x] The "Handler" singleton system might not be the best, some of the classes can become static, while others should have one instance per game and be reset once the game ends.
- [x] if the recording is meant to be separately given out to people, maybe it should be moved to it's own project or at least namespace

**Comment by ScrubN** [comment]
Honestly, it would be nice if we brought back dependency injection. I would like to add a debug window to allow for modifying values without restarting the game and the ability to inject a settings object on every match would be much more elegant than coupling every handler component to the debug window.

**Comment by ScrubN** [comment]
In hindsight, dependency injection won't entirely solve this issue. For example if I want to add a button to force restart the pathfinding method because it stopped for whatever reason, I will either need to make the method public or use reflection.

**Comment by AlexejheroYTB** [comment]
I have a debug window implemention that I can copy paste from a different mod, I will add that and then we can fill it with useful methods
