### ISSUE TITLE
Record if the player is alive and current roles

### ISSUE THREAD

**Issue by Vedal987** [VedalAI/neuro-amongus#52]
Should record more roles than just imposter in case we need it in the future. Recording if the player is alive or not will be very useful for constructing training data.

**Comment by Alexejhero** [comment]
I thought that you want all neural network communication to be disabled once the player is dead

**Comment by Vedal987** [comment]
> I thought that you want all neural network communication to be disabled once the player is dead

Yes but for that reason we only want training data from when the player is alive, so either we only record data when the player is alive or we record if the player is alive or not and simply exclude that data when training the AI.

**Comment by Alexejhero** [comment]
Already implemented.

We are already recording these fields in HeaderFrame, and if the player is dead we're not sending any data currently.
