### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by jbomhold3** [VedalAI/neuro-amongus#58]
I didn't want to just at you in Discord. If you didn't know VS has a copilot extension. Control + Alt + Enter will show the extra solutions. Save you some back and forth between VSCode and VS.

**Comment by Alexejhero** [comment]
![IMG_20230507_194443](https://user-images.githubusercontent.com/32238504/236693846-896a109e-0d0a-44a4-8fc9-c5f8e34da1be.jpg)
