### ISSUE TITLE
Sabotage data is inconsistent when training

### ISSUE THREAD

**Issue by krogenth** [VedalAI/neuro-amongus#59]
Currently, we convert all recorded data into dictionaries to avoid unnecessary load times performing conversions while defaulted data uses the `data.proto_defaults` definitions where applicable.

This becomes an issue when starting to convert during training, where a recorded sabotage is a dictionary goes through `convert_dict`, but the defaulted `TaskData` goes through `convert_taskdata`, resulting in misaligned array dimensions.

Attached is a recording with some sabotage data if necessary for testing.

[133264897257692422.zip](https://github.com/VedalAI/neuro-amongus/files/11424977/133264897257692422.zip)

**Comment by krogenth** [comment]
Looked into it more, a run without the decoded version of the `gymbag2` file will run perfectly fine, but attempting to run with the decoded version already made will result in the issue described.

**Comment by Alexejhero** [comment]
Related: https://github.com/danielgtaylor/python-betterproto/issues/475

**Comment by krogenth** [comment]
Depends on what we _want_ to have our data as. My understanding was that we wanted to be using the betterproto definitions made, but always using them was too costly to convert to. If we actually want to be using the `attr_dict`, we'd get unnecessary data fed into the model(mostly the `id` and `type` of the task).

**Comment by Alexejhero** [comment]
So the problem is that the two datasets are different, the easiest solution would be to load the dictionary even in the first run, when first caching the file. 

This however brings a new problem, everything is just dictionaries instead of types and the convert functions lose meaning.

**Comment by krogenth** [comment]
We might also need to covert from `proto_defaults` to dict defaults as well, unless there's a non-performance heavy way to treat/convert the proto classes as dict.

**Comment by Alexejhero** [comment]
This is no longer a problem as we're now saving the entire Game as a pickle file.
