### ISSUE TITLE
Enhancement: Steam Play compatibility 

### ISSUE THREAD

**Issue by mm12** [VedalAI/neuro-amongus#61]
Provide working instructions for the plugin to work when using steam play. 

I have tried several methods from https://www.reddit.com/r/SteamDeck/comments/whwgkp/comment/ilv4z04/?utm_source=share&utm_medium=web2x&context=3 but none of them have worked with the pluggin yet.

**Comment by ScrubN** [comment]
BepInEx IL2CPP Linux: https://builds.bepinex.dev/projects/bepinex_be/668/BepInEx-Unity.IL2CPP-linux-x64-6.0.0-be.668%2B46e297f.zip

**Comment by mm12** [comment]
> BepInEx IL2CPP Linux: https://builds.bepinex.dev/projects/bepinex_be/668/BepInEx-Unity.IL2CPP-linux-x64-6.0.0-be.668%2B46e297f.zip

i will try this but i have heard it doesn't work

**Comment by mm12** [comment]
No it did not work.

**Comment by ScrubN** [comment]
I will try on Linux later today when I am free.

**Comment by mm12** [comment]
Related: https://www.gamingonlinux.com/2022/07/among-us-modding-on-steam-deck-is-quite-easy-heres-a-quick-guide/

**Comment by mm12** [comment]
UPDATE: 
I finally got something to happen: "failed to start BepInEx" - gonna try some things

**Comment by mm12** [comment]
Update: the preloader error log trace is an IOException in ConsolePal all the way down into Doorstop.Entrypoint.Start - line 39

Gonna try this https://docs.bepinex.dev/master/articles/advanced/steam_interop.html#open-winecfg-for-the-target-game

**Comment by mm12** [comment]
I got it to run by changing proton version - but then it crashed - the error log in BepInEx says 
`Fatal error. Internal CLR error. (0x80131506)`
`Unhandled exception. System.ExecutionEngineException: Exception of type 'system.ExecutionEngineException' was thrown.`

**Comment by mm12** [comment]
If I use the newest pre-release of BepInEx, the game starts but BepInEx doesn't load
If I use the one in the ZIP, BepInEx loads but crashes

**Comment by mm12** [comment]
Error logs attached 
[ErrorLog.log](https://github.com/VedalAI/neuro-amongus/files/11535767/ErrorLog.log)
[LogOutput.log](https://github.com/VedalAI/neuro-amongus/files/11535768/LogOutput.log)

**Comment by mm12** [comment]
[Issue/error report](https://github.com/BepInEx/BepInEx/issues/616) opened in BepInEx since it seems to be a problem there

**Comment by Alexejhero** [comment]
So unfortunately there's nothing we can do on our end to add compatibility for Steam Play. Neither me nor Vedal use anything but Windows and it would be a lot of effort to try to fix this. 

The issue was cross-posted in the BepInEx repo, so I hope it will be resolved there (maybe it should be in the Cpp2IL repo as well? no idea)

If you are able to fix this issue or come up with a workaround, feel free to let us know and we'll add the instructions to the readme.

**Comment by mm12** [comment]
Solved: I did some stuff with removing the launch commands for first run, now it works

**Comment by Alexejhero** [comment]
@mm12 I'm glad to hear that you were able to solve it.
