### ISSUE TITLE
(Question) about dataset to help train the AI

### ISSUE THREAD

**Issue by andresnowak** [VedalAI/neuro-amongus#79]
I have a question regarding contributing to the training of our AI model, specifically in relation to the neural network and dataset:
1. How can someone contribute to the training of the AI model, particularly in the area of the neural network?
2. Where can I access the dataset required for training the AI model? Or If someone wants to help in this area they should use the recordings from their own games for the dataset?

**Comment by Alexejhero** [comment]
1. The model is trained by vedal using the data collected and provided by various people using the mod. In that regard, there is no way to help with the actual training, but if you have any contributions that you would like to make to the neural network architecture, the source code for it is available in this repository in the AI folder.
2. Currently the dataset is not publicly accessible, as it is only stored locally on the upload server. As a result of that, only vedal has access to it and can use it to train the model. That being said, we believe that we have already

**Comment by andresnowak** [comment]
Okay, and thank you for answering.
